### ISSUE TITLE
VirtualMouseModule: support for groups

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/whs.js#273]
The current version of `VirtualMouseModule` doesn't support groups and children.

**Temporary workaround**:

```js
mouseModule.intersection = function(component) {
	const rc = this.raycaster;

	let singleObject = true;
	let object = component.native;
	let objects = [];

	if (object.children.length > 0) {
		singleObject = false;

		object.traverse(child => {
			objects.push(child);
		})
	}

  return singleObject ? rc.intersectObject(object) : rc.intersectObjects(objects);
}

mouseModule.hovers = function(component) {
	return this.intersection(component).length > 0;
}
```

**TODO**:

- [x] Support for nested objects
  - [x] `.intersection()` for children

###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [ ] Bug
 - [x] Proposal/Enhancement
 - [ ] Question
 - [ ] Discussion

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>
